### ISSUE TITLE
deposit the website

### ISSUE THREAD

**Issue by RenhaoL** [datasome/cellphonedbviz#11]
Hi there, 

A great addition to CellphoneDB! I was wondering how to deposit the website to a publicly available server. Can users deploy a website associated with a publication? 

Thanks in advance,
Renhao

**Comment by jessica-cox** [comment]
Hi Renhao,

Thank you for your message. You should be able to host and administrate your own cpdbviz using the code in this repository. You will also need a zipped copy of the version of cellphonedb you wish to use for each visualisation for this. Let me know if anything is unclear and I will do my best to help.

Kind regards,
Jessica

**Comment by ashleighthomas** [comment]
Hi Jessica,

I am also having issues administering my own cpdbviz. Could you please see this issue: https://github.com/ventolab/cellphonedbviz/issues/25? Thank you!
