### ISSUE TITLE
Reg: No access to projects in https://www.cellphonedb.org/viz/index.html

### ISSUE THREAD

**Issue by Poonam02-ai** [datasome/cellphonedbviz#2]
Dear Ventolab Team,
I am Poonam Sarode.
I am trying to access the projects in https://www.cellphonedb.org/viz/index.html.
When I click on the listed projects, I get the message "Sorry, you don't have access to this page."
Please let me know what actions I need to take to get access to these projects.
Thanks and Regards, 
Poonam

**Comment by jessica-cox** [comment]
Hi Poonam,

This is usually the case when the data you are trying to view is private. What do you want to see?

Jess

**Comment by prete** [comment]
Hi @Poonam02-ai, two open projects you can look at are:
https://www.cellphonedb.org/viz/viz.html?projectid=gonads_cpdbv5_deg
https://www.cellphonedb.org/viz/viz.html?projectid=endometrium_cpdbv5_stat_v5.1
